apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-client-config
  namespace: {{.Values.namespace}}
data:
    NODE_ENV: "production"
    VITE_BASE_URL: {{.Values.deployment.client.base_url}}