apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-server-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.name}}-server
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP