apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-client-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.name}}-client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP