apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
  namespace: {{.Values.namespace}}
stringData:
  PORT : "5000"
  JWT_SECRET: "secret"
  MONGO_CONNECTION_URI: "mongodb://root:password@store-mongodb-0.store-mongodb-headless.{{.Values.namespace}},store-mongodb-1.store-mongodb-headless.{{.Values.namespace}},store-mongodb-2.store-mongodb-headless.{{.Values.namespace}}:27017"